version: "3.3"
services:
  app:
    build: .
    volumes:
      - type: bind
        source: /home/ubuntu/bots_config/chika-faq-bot/config
        target: /chika_faq_bot/config
      - type: bind
        source: /var/log/chika-faq-bot
        target: /chika_faq_bot/logs
    network_mode: "host"
    restart: unless-stopped
    ports:
      - "9310:9310"